### PR TITLE
switch to use psr-4

### PR DESCRIPTION
**Pull request by hairmare**
Less clutter and a simpler autoloader seem to make the case for replacing PSR-0 with PSR-4.

This should not have any influence on downstream users.

### CODE REVIEW

**Comment by hairmare** [comment]
@narcoticfresh is this ok with you?

**Comment by hairmare** [comment]
@narcoticfresh Could look over this?

I really don't care which way we decide but need a decision so I can move along with #11.

**Comment by narcoticfresh** [comment]
Ah I'm sorry, this was assigned to me long time ago..
Yes I'm fine, don't see any downside with switching to PSR-4..

**Comment by hairmare** [comment]
cool, thanks

**Pull request merged**
